import numpy as np
import warnings


# Given a node in a graph, return all the connected nodes to this node
# Update visited_nodes list to reflect the visited nodes during this process
# mat must be square, symmetric, undirected, and binary
def _dfs_single_comp(
    mat: np.ndarray,
    visited_nodes: np.ndarray | None = None,
    cur_node: int = 0,
) -> list[int]:

    # Initialize visited_nodes if this is a one-off use.
    if visited_nodes is None:
        visited_nodes = np.zeros(len(mat))
    
    
    assert len(mat) == len(visited_nodes)
    assert visited_nodes[cur_node] != 1

    visited_nodes[cur_node] = 1
    component_nodes = [cur_node]

    # For all the neighbors of a node...
    for neighbor_index in np.where(mat[cur_node] == 1)[0]:
        # If it hasnt been visited yet...
        if visited_nodes[neighbor_index] == 0:
            # Visit it! And add it and all its children to the parent node group
            component_nodes = component_nodes + _dfs_single_comp(mat, visited_nodes, neighbor_index)
        
    return component_nodes


def preprocess_karger(
    aff_mat: np.ndarray,
    binary_boundary: float,
) -> tuple[np.ndarray, list[list[int]]]:
    """Prune and binarize an affinity matrix and find the connected components of the resulting graph.

    Converts the complete affinity matrix to a sparser binary adjacency matrix ready for 
    Karger's algorithm. Removes all self-edges and edges below ``binary_boundary``, and
    identifies all separately connected components in the resulting graph.

    Args:
        aff_mat (np.ndarray): Square, symmetric affinity matrix representing
            pairwise molecular similarities.
        binary_boundary (float): Similarity threshold used to determine whether
            an edge should remain in the pruned matrix. Pairs with similarity
            greater than this value remain connected.

    Returns:
        tuple[np.ndarray, list[list[int]]]: A tuple containing the pruned
            binary adjacency matrix and a list of connected components. Each
            connected component is represented by a list of indices.
    """

    # Binarized matix... important that this is the type of integer. If it is boolean, then 
    # 1 + 1 = True + True = 1, not 2. This will break Karger's algorithm, as it relies on
    # changing edge weight for selection
    mat = (aff_mat > binary_boundary).astype(int)

    # Self edges are not expected for karger's algoritm 
    np.fill_diagonal(mat, 0)

    # Initialize no visited nodes and no connected components
    visited_nodes = np.zeros(len(mat))
    components = []

    # While there are nodes to be visited
    while 0 in visited_nodes:

        # Find an unvisited node
        next_node = np.where(visited_nodes == 0)[0][0]

        # Find the whole component that node belongs to (unvisited connected component)
        component = _dfs_single_comp(mat, visited_nodes, next_node)

        # Add to the list
        components.append(component)

    return mat, components


def generate_karger(
    adj_mat: np.ndarray,
    components: list[list[int]],
    test_frac: float,
    seed: int,
    tol: float = 0.01,
) -> tuple[list[int], list[int]]:
    """Generate a train/test split using a modified Karger's algorithm.

    Assigns complete connected components to the test and training sets until
    one component remains to be split. The nodes of the remaining component are
    repeatedly merged by randomly selecting edges until a supernode reaches
    sufficient size.

    The adjacency matrix is modified in-place during the contraction process.
    Pass a copy if the original matrix cannot be altered.

    Args:
        adj_mat (np.ndarray): Binary adjacency matrix representing
            the molecular similarity graph. The matrix is modified in-place.
            Must be numeric, not boolean.
        components (list[list[int]]): Connected components of ``adj_mat``,
            typically generated by ``preprocess_karger``.
        test_frac (float): The proportion of the dataset that the test set should
            represent. Strictly between 0 and 1.
        seed (int): Random seed used for shuffling connected components and
            selecting edges.
        tol (float): The maximum allowed deviation from the target test
            proportion.

    Raises:
        ValueError: If ``test_frac`` is not strictly between 0 and 1.
        TypeError: If ``adj_mat`` does not contain integer values.

    Returns:
        tuple[list[int], list[int]]: A tuple containing two mutually exclusive
            lists: (train_indices, test_indices).
    """

    if not 0 < test_frac < 1:
        raise ValueError(f"test_frac must be in (0, 1), got {test_frac}")

    if not np.issubdtype(adj_mat.dtype, np.integer):
        raise TypeError(f"adj_mat must contain integers, got dtype {adj_mat.dtype}")


    # Because this list will be modified in-place
    components = components.copy()

    gen = np.random.default_rng(seed)

    # Number of molecules
    NUM_NODES = len(adj_mat)
    TARGET_TEST_SIZE = round(test_frac * NUM_NODES)

    # Sort connected components by largest --> smallest, with a random order to break ties
    gen.shuffle(components)
    components.sort(key=len, reverse=True)

    
    # ========================================= FIND THE COMPONENT TO SPLIT =======================================================


    # Greedily add the smallest connected components to the test set until more would exceed the target size
    test = []

    # While there are free components...
    while len(components) > 1:

        # If adding the smallest component would be too big for the test, stop
        if len(test) + len(components[-1]) > TARGET_TEST_SIZE:
            break
        # Otherwise, the next component fits, so add it
        else:
            test = test + components.pop()


    # Pick the next smallest component to be split. There exists some fraction < 1 of this component that can bring the test up to the target size
    component_to_split = components.pop()

    # Add remaining components to train
    train = []
    while len(components) > 0:
        train = train + components.pop()

    # Remove all but the to-be-split component from the graph
    for i in train + test:
        adj_mat[i, :] = 0
        adj_mat[:, i] = 0

    # ===================================================================================================================================

    # Stop the algorithm once a supernode reaches this size
    SUPERNODE_CUTOFF = TARGET_TEST_SIZE - len(test)

    # Number of nodes +- from the target size that should be allowed in the test set 
    SUPERNODE_TOL = round(tol * TARGET_TEST_SIZE)

    MIN_SUPERNODE_SIZE = round(SUPERNODE_CUTOFF - SUPERNODE_TOL)
    MAX_SUPERNODE_SIZE = round(SUPERNODE_CUTOFF + SUPERNODE_TOL)


    # Each node starts off on its own (N supernodes), and they will merge until one supernode reaches SUPERNODE_CUTOFF size
    supernodes = [{i} for i in component_to_split]

    # Dont split a single-noded component!
    if len(supernodes) == 1:
        test = test + list(supernodes[0])
        train = [i for i in range(0, NUM_NODES) if i not in test]
        return train, test
        
    
    # While there are more than two supernodes to be merged
    while len(supernodes) > 2:


        p, q = _select_rand_edge(adj_mat, gen)


        # Merge nodes p and q into a supernode
        # Opportunity for multi-threading:
        _merge_nodes(p, q, adj_mat)
        new_supernode = _merge_sets(p, q, supernodes)

        # TODO: Make this propely incorporate the tolerance
        # If the supernode is of suitable size:
        if len(new_supernode) >= MIN_SUPERNODE_SIZE:

            if len(new_supernode) > MAX_SUPERNODE_SIZE:
                warnings.warn(f"The supernode is {len(new_supernode) - MAX_SUPERNODE_SIZE} molecules outside the tolerance range")
                # What should be done in this case?
            
            test = test + list(new_supernode)

            train = [i for i in range(0, NUM_NODES) if i not in test]
            
            return train, test

    # Classical end to karger's algorithm
    # The two remaining supernodes would form the candidate cut

    # Instead, how we handle it:
    # Since neither supernode is large enough, add them both (will be large enough)
    # This is not the ideal way to handle it, but works for now.
    # What should be done in this case?

    warnings.warn("Karger's merged as far as allowed without finding a suitable supernode. Adding the entire component")
    test = test + list(supernodes[0]) + list(supernodes[1])

    train = [i for i in range(0, NUM_NODES) if i not in test]
    
    return train, test



    # NOTE: I think adjacency lists could be better. 
    # If we describe the graph as a dict of set to list:
    # {   {a}: [b, c]             a (unmerged) is connected to b and c,
    #           ...
    #    {w, x}: [y, z, c]           Supernode {w, x} is connected to y, z, and c
    # Thus, merging {a} and {w, x} is easy:
    # {   ({a} U {w, x}): ([b, c] + [y, z, c])   }
    # = { ({a, w, x}): ([y, z, b, c, c])   }        Importantly, the list properly counts the double edges to c
    # However, its important to note that, in the first part:
    # { ...
    #   {y}: [..., w, x, ...]
    #   ... }
    # And then in the second part:
    #  {  {y}: [..., w, x, a, ... ]  }
    # This may be what your code does, Bryn, but I was having some difficulty understanding it exactly.
    # At our meeting I will ask for a description of your exact method


# Picks a random weighted edge
def _select_rand_edge(adj_mat, gen):
    
    # Find the probablity of the selction being in a certain column and pick a column accordingly
    col_sums = np.sum(adj_mat, axis=0)
    mat_total = np.sum(col_sums)

    assert mat_total != 0, "The graph has no edges"
    
    col_idx = gen.choice(len(adj_mat), p=(col_sums / mat_total))

    # From the selected column choose a weighted random value
    col = adj_mat[:, col_idx]
    row_idx = gen.choice(len(adj_mat), p=(col / np.sum(col)))

    return row_idx, col_idx


# Merges nodes i and j into one supernode in the adjacency matrix, adding the weights of merged edges
# The supernode becomes represented by i, and j loses all connections
def _merge_nodes(i, j, upper_mat):

    NUM_NODES = len(upper_mat)

    # Break the edge between i and j
    upper_mat[i, j] = 0
    upper_mat[j, i] = 0

    for k in range(NUM_NODES):

        
        # Aggregate the edges, increasing the weight of all i-edges in accordance with the correspoinding j-edge
        upper_mat[i, k] += upper_mat[j, k]
        upper_mat[k, i] += upper_mat[k, j]

        # Remove all j-edges, leaving j floating sad and alone
        upper_mat[j, k] = 0
        upper_mat[k, j] = 0




# Merges the set containing val1 with the set containing val2
# Will update set_list to contain the new set and remove the old sets
# Returns the new set
def _merge_sets(val1, val2, set_list):


    set1 = None
    set2 = None
    
    for mol_set in set_list:
        
        if val1 in mol_set:
            # Found the set of value 1
            set1 = mol_set
            
            if set2 != None:
                break
        elif val2 in mol_set:
            # Found the set of value 2
            set2 = mol_set

            if set1 != None:
                break

    # Add all of set2 to set1
    set1.update(set2)

    # Remove set2
    set_list.remove(set2)

    return set1

    

    
            